# change the followings to match your Github username and repo name
baseurl: "/black-womens-labor" # the name of your github repo
url: "https://BCDigSchol.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Black Women's Labor"
description: "Jekyll site for the Black Women's Labor Project @ Boston College"

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# nav bar settings and links
nav-menu:
  - title: Home
    link: index
  - title: Census Information
    link: census
  - title: Records
    link: records
  - title: People
    submenu:
      - title: Christobel Carey
        link: people/christobel-carey
      - title: Marion Hall
        link: people/marion-hall
      - title: Mary Louise Wallace
        link: people/mary-louise-wallace
      - title: Melnea Agnes Cass
        link: people/melnea-agnes-cass
  - title: Further Readings
    link: further-readings

# sets whether a search bar appears on the site header
# NOTE, you will have to increase the site of teh $site-header-height in _sass/theme-settings.scss to to see the search bar
search-bar: false

hide-footer: false # set to true to hide the footer
footer-message: "Black Women's Labor | CC BY-NC License"
footer-submessage:  By Bailey Lemoine, with the Digital Scholarship Group, Boston College
footer-submessage-link: https://ds.bc.edu

# google-analytics: // if you want to use Google analytics, include your ID here

# sets number of items display per page, if using a blog
paginate: 5

include:
  - _pages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
    - jekyll-postcss-v2
